/**
 * Partner API
 * ## Version 5.4.0-SNAPSHOT  ## Information * This service provides an API to manage partners and their related subdomains   ## Contact <b>Authors</b>   <p>     <a href=\"mailto:sdd@vaudoise.ch\">SDD</a>     <a href=\"mailto:jue@vaudoise.ch\">JUE</a>     <a href=\"mailto:gme@vaudoise.ch\">GME</a>     <a href=\"mailto:sdt@vaudoise.ch\">SDT</a>     <a href=\"mailto:hua@vaudoise.ch\">HUA</a>     <a href=\"mailto:emp@vaudoise.ch\">EMP</a>     <a href=\"mailto:rla@vaudoise.ch\">RLA</a> </p>   ___ 
 *
 * OpenAPI spec version: v5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ErrorResponse } from '../model/errorResponse';
import { Leisure } from '../model/leisure';
import { LeisureCategory } from '../model/leisureCategory';
import { LeisureCreationDto } from '../model/leisureCreationDto';
import { PartnerLeisure } from '../model/partnerLeisure';
import { ValidationResponse } from '../model/validationResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class LeisuresService {

    protected basePath = 'https://msvc-partenaire-dev.vaudoise.ch:35361/v5';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add new leisure to a partner
     * 
     * @param leisureCreationDto leisureCreationDto
     * @param policyHolderId policyHolderId
     * @param acceptLanguage Language
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createLeisureUsingPOST(leisureCreationDto: LeisureCreationDto, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public createLeisureUsingPOST(leisureCreationDto: LeisureCreationDto, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public createLeisureUsingPOST(leisureCreationDto: LeisureCreationDto, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public createLeisureUsingPOST(leisureCreationDto: LeisureCreationDto, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (leisureCreationDto === null || leisureCreationDto === undefined) {
            throw new Error('Required parameter leisureCreationDto was null or undefined when calling createLeisureUsingPOST.');
        }

        if (policyHolderId === null || policyHolderId === undefined) {
            throw new Error('Required parameter policyHolderId was null or undefined when calling createLeisureUsingPOST.');
        }


        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/partners/${encodeURIComponent(String(policyHolderId))}/leisures`,
            leisureCreationDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Remove leisure from partner
     * 
     * @param leisureId leisureId
     * @param policyHolderId policyHolderId
     * @param acceptLanguage Language
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteLeisureUsingDELETE(leisureId: string, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteLeisureUsingDELETE(leisureId: string, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteLeisureUsingDELETE(leisureId: string, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteLeisureUsingDELETE(leisureId: string, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (leisureId === null || leisureId === undefined) {
            throw new Error('Required parameter leisureId was null or undefined when calling deleteLeisureUsingDELETE.');
        }

        if (policyHolderId === null || policyHolderId === undefined) {
            throw new Error('Required parameter policyHolderId was null or undefined when calling deleteLeisureUsingDELETE.');
        }


        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/partners/${encodeURIComponent(String(policyHolderId))}/leisures/${encodeURIComponent(String(leisureId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve a specific leisure of a partner
     * 
     * @param leisureId leisureId
     * @param policyHolderId policyHolderId
     * @param acceptLanguage Language
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPartnerLeisureUsingGET(leisureId: string, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'body', reportProgress?: boolean): Observable<PartnerLeisure>;
    public getPartnerLeisureUsingGET(leisureId: string, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PartnerLeisure>>;
    public getPartnerLeisureUsingGET(leisureId: string, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PartnerLeisure>>;
    public getPartnerLeisureUsingGET(leisureId: string, policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (leisureId === null || leisureId === undefined) {
            throw new Error('Required parameter leisureId was null or undefined when calling getPartnerLeisureUsingGET.');
        }

        if (policyHolderId === null || policyHolderId === undefined) {
            throw new Error('Required parameter policyHolderId was null or undefined when calling getPartnerLeisureUsingGET.');
        }


        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PartnerLeisure>(`${this.basePath}/partners/${encodeURIComponent(String(policyHolderId))}/leisures/${encodeURIComponent(String(leisureId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve the list of leisures of a partner
     * 
     * @param policyHolderId policyHolderId
     * @param acceptLanguage Language
     * @param isActive isActive
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listByPartnerUsingGET(policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', isActive?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<PartnerLeisure>>;
    public listByPartnerUsingGET(policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', isActive?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PartnerLeisure>>>;
    public listByPartnerUsingGET(policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', isActive?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PartnerLeisure>>>;
    public listByPartnerUsingGET(policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', isActive?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (policyHolderId === null || policyHolderId === undefined) {
            throw new Error('Required parameter policyHolderId was null or undefined when calling listByPartnerUsingGET.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (isActive !== undefined && isActive !== null) {
            queryParameters = queryParameters.set('isActive', <any>isActive);
        }

        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<PartnerLeisure>>(`${this.basePath}/partners/${encodeURIComponent(String(policyHolderId))}/leisures`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve the list of categories of leisures
     * 
     * @param acceptLanguage Language
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listCategoriesUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'body', reportProgress?: boolean): Observable<Array<LeisureCategory>>;
    public listCategoriesUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<LeisureCategory>>>;
    public listCategoriesUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<LeisureCategory>>>;
    public listCategoriesUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<LeisureCategory>>(`${this.basePath}/leisure-categories`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve the list of leisures
     * 
     * @param acceptLanguage Language
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'body', reportProgress?: boolean): Observable<Array<Leisure>>;
    public listUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Leisure>>>;
    public listUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Leisure>>>;
    public listUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<Leisure>>(`${this.basePath}/leisures`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
