/**
 * Partner API
 * ## Version 5.4.0-SNAPSHOT  ## Information * This service provides an API to manage partners and their related subdomains   ## Contact <b>Authors</b>   <p>     <a href=\"mailto:sdd@vaudoise.ch\">SDD</a>     <a href=\"mailto:jue@vaudoise.ch\">JUE</a>     <a href=\"mailto:gme@vaudoise.ch\">GME</a>     <a href=\"mailto:sdt@vaudoise.ch\">SDT</a>     <a href=\"mailto:hua@vaudoise.ch\">HUA</a>     <a href=\"mailto:emp@vaudoise.ch\">EMP</a>     <a href=\"mailto:rla@vaudoise.ch\">RLA</a> </p>   ___ 
 *
 * OpenAPI spec version: v5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { BaseRelation } from '../model/baseRelation';
import { ErrorResponse } from '../model/errorResponse';
import { PartnerRelation } from '../model/partnerRelation';
import { ValidationResponse } from '../model/validationResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PartnerRelationsService {

    protected basePath = 'https://msvc-partenaire-dev.vaudoise.ch:35361/v5';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a new relation between 2 partners
     * 
     * @param relationDto relationDto
     * @param acceptLanguage Language
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createRelationUsingPOST(relationDto: BaseRelation, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'body', reportProgress?: boolean): Observable<PartnerRelation>;
    public createRelationUsingPOST(relationDto: BaseRelation, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PartnerRelation>>;
    public createRelationUsingPOST(relationDto: BaseRelation, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PartnerRelation>>;
    public createRelationUsingPOST(relationDto: BaseRelation, acceptLanguage?: 'FR' | 'DE' | 'IT', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (relationDto === null || relationDto === undefined) {
            throw new Error('Required parameter relationDto was null or undefined when calling createRelationUsingPOST.');
        }


        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PartnerRelation>(`${this.basePath}/relations`,
            relationDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a relation between 2 partners
     * 
     * @param id id
     * @param acceptLanguage Language
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteRelationUsingDELETE(id: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteRelationUsingDELETE(id: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteRelationUsingDELETE(id: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteRelationUsingDELETE(id: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteRelationUsingDELETE.');
        }


        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/relations/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve a relation from a given Id
     * 
     * @param id id
     * @param acceptLanguage Language
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRelationUsingGET(id: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'body', reportProgress?: boolean): Observable<PartnerRelation>;
    public getRelationUsingGET(id: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PartnerRelation>>;
    public getRelationUsingGET(id: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PartnerRelation>>;
    public getRelationUsingGET(id: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getRelationUsingGET.');
        }


        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PartnerRelation>(`${this.basePath}/relations/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve the list of relations for a given partner and type
     * 
     * @param acceptLanguage Language
     * @param policyHolderId Partner Policy Holder Id
     * @param type Type of the relation
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listRelationsUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', policyHolderId?: number, type?: 'family' | 'ownership' | 'proxy', observe?: 'body', reportProgress?: boolean): Observable<Array<PartnerRelation>>;
    public listRelationsUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', policyHolderId?: number, type?: 'family' | 'ownership' | 'proxy', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PartnerRelation>>>;
    public listRelationsUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', policyHolderId?: number, type?: 'family' | 'ownership' | 'proxy', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PartnerRelation>>>;
    public listRelationsUsingGET(acceptLanguage?: 'FR' | 'DE' | 'IT', policyHolderId?: number, type?: 'family' | 'ownership' | 'proxy', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (policyHolderId !== undefined && policyHolderId !== null) {
            queryParameters = queryParameters.set('policyHolderId', <any>policyHolderId);
        }
        if (type !== undefined && type !== null) {
            queryParameters = queryParameters.set('type', <any>type);
        }

        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<PartnerRelation>>(`${this.basePath}/relations`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a relation between 2 partners
     * 
     * @param id id
     * @param relationDto relationDto
     * @param acceptLanguage Language
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateRelationUsingPUT(id: number, relationDto: BaseRelation, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'body', reportProgress?: boolean): Observable<PartnerRelation>;
    public updateRelationUsingPUT(id: number, relationDto: BaseRelation, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PartnerRelation>>;
    public updateRelationUsingPUT(id: number, relationDto: BaseRelation, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PartnerRelation>>;
    public updateRelationUsingPUT(id: number, relationDto: BaseRelation, acceptLanguage?: 'FR' | 'DE' | 'IT', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling updateRelationUsingPUT.');
        }

        if (relationDto === null || relationDto === undefined) {
            throw new Error('Required parameter relationDto was null or undefined when calling updateRelationUsingPUT.');
        }


        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<PartnerRelation>(`${this.basePath}/relations/${encodeURIComponent(String(id))}`,
            relationDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
