/**
 * Partner API
 * ## Version 5.4.0-SNAPSHOT  ## Information * This service provides an API to manage partners and their related subdomains   ## Contact <b>Authors</b>   <p>     <a href=\"mailto:sdd@vaudoise.ch\">SDD</a>     <a href=\"mailto:jue@vaudoise.ch\">JUE</a>     <a href=\"mailto:gme@vaudoise.ch\">GME</a>     <a href=\"mailto:sdt@vaudoise.ch\">SDT</a>     <a href=\"mailto:hua@vaudoise.ch\">HUA</a>     <a href=\"mailto:emp@vaudoise.ch\">EMP</a>     <a href=\"mailto:rla@vaudoise.ch\">RLA</a> </p>   ___ 
 *
 * OpenAPI spec version: v5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ErrorResponse } from '../model/errorResponse';
import { SupplierBusiness } from '../model/supplierBusiness';
import { ValidationResponse } from '../model/validationResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SuppliersService {

    protected basePath = 'https://msvc-partenaire-dev.vaudoise.ch:35361/v5';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Retrieve a supplier&#39;s data
     * 
     * @param policyHolderId policyHolderId
     * @param acceptLanguage Language
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSupplierDataUsingGET(policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'body', reportProgress?: boolean): Observable<Array<SupplierBusiness>>;
    public getSupplierDataUsingGET(policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SupplierBusiness>>>;
    public getSupplierDataUsingGET(policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SupplierBusiness>>>;
    public getSupplierDataUsingGET(policyHolderId: number, acceptLanguage?: 'FR' | 'DE' | 'IT', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (policyHolderId === null || policyHolderId === undefined) {
            throw new Error('Required parameter policyHolderId was null or undefined when calling getSupplierDataUsingGET.');
        }


        let headers = this.defaultHeaders;
        if (acceptLanguage !== undefined && acceptLanguage !== null) {
            headers = headers.set('Accept-Language', String(acceptLanguage));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<SupplierBusiness>>(`${this.basePath}/suppliers/${encodeURIComponent(String(policyHolderId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
